export const courseList = [
    "Certified Scrum Master (CSM®) Certification Training",
    "Disciplined Agile Foundations (DAF) Online Training",
    "Cognitive Project Management in AI (CPMAI) Certification Training",
    "Certified Scrum Product Owner (CSPO®) Certification Training",
    "Advanced Certified Scrum Master (A-CSM®) Certification Training",
    "Advanced Certified Scrum Product Owner (A-CSPO®) Certification Training",
    "Certified Scrum Developer (CSD®) Certification Training",
    "Agile and Scrum Training",
    "PMI-Agile Certified Practitioner (PMI-ACP®) Certification Training",
    "Professional Scrum Master™ (PSM I) Certification Training",
    "Certified Agile Scaling Practitioner 1 (CASP 1) Training",
    "Agile Coaching Skills - Certified Facilitator (CAF) Training",
    "Professional Scrum Master™ Advanced (PSM A) Certification Training",
    "Certified Agile Leader® 1 (CAL 1™) Certification Training",
    "Advanced-Certified Scrum Developer® (A-CSD) Certification Training",
    "ICAgile Certified Professional in Agile Coaching (ICP-ACC®) Certification Training",
    "Professional Scrum with Kanban™ (PSK) Certification Training",
    "Professional Scrum Product Owner™ I (PSPO) Certification Training",
    "Professional Scrum Developer (PSD) Certification Training",
    "Certified Scrum Professional - ScrumMaster (CSP®-SM) Certification Training",
    "Certified Agile Leader® 2 (CAL 2™) Certification Training",
    "Scrum@Scale™ Certification Training",
    "Kanban System Design (KMP I) Certification Training",
    "Team Kanban Practitioner (TKP) Certification Training",
    "Professional Agile Leadership Essentials™ (PAL-E) Certification Training",
    "Agile Objectives and Key Results (Agile OKRs) MicroCredential Training",
    "Agile Management 3.0 Training",
    "Behaviour Driven Development (BDD) Training",
    "Test Driven Development (TDD) Training",
    "Agile Fundamentals : Including Scrum and Kanban Training",
    "Manage Agile Projects Using Scrum Training",
    "Agile for Executives Training",
    "Agile for Managers Training",
    "Agile Product Owner Training",
    "Agile Sales Management Training",
    "Applying Professional Scrum™ (APS) Certification Training",
    "Agile Release Planning Training",
    "Disciplined Agile® Scrum Master (DASM) Certification Training",
    "Disciplined Agile Senior Scrum Master (DASSM) Certification Training",
    "Certified Scrum Professional - Product Owner® (CSP-PO) Certification Training",
    "Agile Project Management Training",
    "Jira Software Training for Agile Projects",
    "Leading SAFe® 6.0 Certification Training",
    "SAFe® 6.0 Scrum Master (SSM) Certification Training",
    "SAFe® 6.0 Product Owner/Product Manager (POPM) Certification Training",
    "SAFe® 6.0 Practice Consultant (SPC) Certification Training",
    "SAFe® 5.1 Advanced Scrum Master (SASM) Certification Training",
    "SAFe® 6.0 Lean Portfolio Management (LPM) Certification Training",
    "SAFe® 6.0 Architects Certification Training",
    "SAFe® 6.0 for Teams Certification Training",
    "SAFe® 6.0 Release Train Engineer (RTE) Certification Training",
    "SAFe® 6.0 DevOps Certification Training",
    "Advanced Facilitator: Conflict & Collaboration Micro-Credential Course",
    "SAFe® 6.0 Agile Product Management (APM) Certification Training",
    "SAFe® 5.0 Agile Software Engineering Certification Training",
    "Advanced Facilitator: Value Stream Mapping Micro-Credential Course",
    "Achieving Responsible AI with SAFe Micro-credential Course",
    "Project Management Professional (PMP®) Certification Training",
    "Project Management Techniques Training",
    "PRINCE2® Foundation and Practitioner Certification Training",
    "PRINCE2® Foundation Certification Training",
    "PRINCE2® Practitioner Certification Training",
    "Certified Associate in Project Management (CAPM®) Certification Training",
    "PRINCE2 Agile® Foundation Certification Training",
    "Primavera P6 v 20.12 certification training",
    "PRINCE2 Agile® Practitioner Certification Training",
    "PRINCE2 Agile® Foundation and Practitioner Certification Training",
    "Program Management Professional (PgMP)® Certification Training",
    "Project Management Fundamental Training",
    "Portfolio Management Professional (PfMP®) Certification Training",
    "Business Case Writing Training",
    "Conflict Management Training",
    "Certified Business Analysis Professional (CBAP®) Certification Training",
    "Change Management Training",
    "Certification of Capability in Business Analysis™ (CCBA®) Training",
    "Business Analytics 360 Training",
    "Entry Certificate in Business Analysis™ (ECBA™) Certification Training",
    "Certificate in Product Ownership Analysis (IIBA®-CPOA) Certification Training",
    "Certificate in Cybersecurity Analysis (IIBA®- CCA) Certification Training",
    "Certification in Business Data Analytics (IIBA®- CBDA) Certification Training",
    "Business Analysis Training",
    "Agile Analysis Certification (IIBA®-AAC) Certification Training",
    "Generative AI for Business & IT Leaders & Managers Training",
    "Generative AI for Business Analysts & Functional IT Consultants Training",
    "Generative AI for Marketing and Sales Business Users Training",
    "Generative AI with Python & AWS Training",
    "AI Copilots for Business Users: Microsoft Copilot, Google Duet AI, AmazonQ",
    "Generative AI with Python and Azure Training",
    "Generative AI with Python and GCP Training",
    "Cloud Fundamentals for Business Managers & Product Managers Training",
    "Generative AI Architect - Advanced Program Training",
    "Multi-cloud FinOps: AWS, GCP, Azure",
    "Introduction to Generative AI Training",
    "Generative AI in HR Certification Course",
    "Generative AI for Software Developers Course",
    "Prompt Engineering Course",
    "Mastering Generative AI Tools Online",
    "Generative AI In Retail Certification Course",
    "DevOps Foundation® Certification Training",
    "Docker and Kubernetes Training",
    "Continuous Testing Foundation (CTF)℠ Certification Training",
    "Continuous Delivery Ecosystem Foundation (CDEF)℠ Certification Training",
    "DevSecOps Foundation℠ Certification Training",
    "ITIL 4® Foundation Certification Training",
    "Lean Six Sigma Yellow Belt Training",
    "Lean Six Sigma Green Belt Training",
    "Lean Six Sigma Black Belt Training",
    "Root Cause Analysis (RCA) Training",
    "Six Sigma Fundamentals Training",
    "AWS SysOps Administrator Certification Training",
    "AWS DevOps Engineer Certification Training",
    "AWS Cloud Practitioner Certification Training",
    "AWS Certified Solutions Architect Professional Certification Training",
    "Data Science With Python Training",
    "Python Django (PD) Training",
    "Introduction to Artificial Intelligence and Machine Learning (AI and ML) Training",
    "Artificial Intelligence (AI) Training",
    "Data Science Training",
    "Big Data Analytics Training",
    "Extreme Programming Practitioner Training",
    "Certified Artificial Intelligence For Agile Leaders Training",
    "Angular JS Training",
    "React Native Training",
    "React JS Training",
    "Introduction to Blockchain Training",
    "Python for Beginners Training",
    "UX Design Training",
    "Snowflake SnowPro Advanced Architect Training",
    "Card Production Security Assessor Qualification Training",
    "Python Programming Training",
    "PCI DSS Training",
    "Payment Application Qualified Security Assessor (PA-QSA) Training",
    "PCI Acquirer Training",
    "Microsoft AZ-400: Designing and Implementing Microsoft DevOps Solutions Training",
    "Microsoft Power BI Training",
    "AZ-104 Microsoft Azure Administrator Training",
    "Certified Information Systems Security Professional (CISSP®) Training",
    "Agile Data Science Boot Camp",
    "Agile Infrastructure Boot Camp Training",
    "Agile Marketing Boot Camp Training",
    "Advanced SAFe Practice Consultant (ASPC) Certification Path",
    "AI for Product Owners Micro-credential Training",
    "AI for Scrum Masters Micro-credential Course",
    "Advanced Scrum Master Certification Path",
    "Microsoft Azure Fundamentals AZ-900 Certification Training",
    "Microsoft Azure Developer Associate (AZ-204) Certification Course",
    "Microsoft Certified Azure Solutions Architect Expert (AZ-305) Certification Training",
    "Generative AI for Scrum Masters Training",
    "Generative AI for Agile Leaders Training",
    "Generative AI for Project Managers Training",
    "Generative AI for Product Owners/Product Managers Certification Training",
    "ICP Agile Fundamentals Certification",
    "ICP-PDV (People Development)",
    "ICP-PDM (Product Management)",
    "ICP-FAI (Foundations of AI)",
    "ICP-ACC (Agile Coaching Certification)",
    "ICP-LEA (Agile Leadership Certification)",
    "ICP-LPM (Lean Portfolio Management)",
    "ICP-SYS (Systems Coaching)",
    "ICP-APM (Agile Project & Delivery Management)",
    "ICP-CAT (Coaching Agile Transformations)",
    "ICP-ATF (Agile Team Facilitation)",
    "ICP-ORG (Adaptive Org Design)",
    "ICP-APO (Agile Product Ownership)",
    "ICP-ENT (Enterprise Agile Coaching)",
    "ICP-ATF (Agile Team Facilitation)",
    "ICP-BAF (Business Agility Foundations)",
    "AI for Customer Insights",
    "AI for Product Discovery",
    "AI for Product Strategy",
    "AI for Product Planning",
    "AI for Product Metrics",
    "AI for Stakeholder Management",
    "Professional Scrum Product Owner (PSPO) - Advanced Course",
    "Others"
  ];
